haskell day 2021 タイムテーブル
haskell-jp/haskell-jp.github.io pull request #32
Opened 2021-07-25 06:29 UTC by nakaji-dayo

2021-07-26 01:49 UTC, igrep requested changes
取り急ぎ一点だけ。 🙇

2021-07-26 01:49 UTC, igrep commented on haskell-day-2021/index.html
> +            <tr><td>13:10~13:55</td><td class="title">招待講演</td><td></td></tr>
せっかくなんで「豪華ゲスト」と書いておきましょう。

2021-07-26 12:27 UTC, igrep commented
他、デザインを手元で確認しました。特に問題ないと思います。

2021-07-26 12:49 UTC, nakaji-dayo commented on haskell-day-2021/index.html
> +            <tr><td>13:10~13:55</td><td class="title">招待講演</td><td></td></tr>
追記しました。
最大幅時での収まりから絵文字は先頭のみにしました

2021-07-27 00:15 UTC, igrep approved these changes
いいと思います！
![うん ホント キュンキュンだよ](https://user-images.githubusercontent.com/227057/127075218-226d629a-a9ca-4fbc-819a-a2bf5057d824.jpg)

2021-07-27 07:26 UTC, kakkun61 commented
@nakaji-dayo この PR あてに見ために手を加えた PR 作りましたー #33

2021-07-28 01:23 UTC, nakaji-dayo commented
@kakkun61 確認しますー！

2021-07-30 03:53 UTC, kakkun61 approved these changes

2021-07-30 04:42 UTC, kakkun61 commented
マージしちゃってください❤️

2021-07-30 14:37 UTC, merged